enum PriceType {
  UNIT
  PACKAGE
  WEIGHT
}
"Price / Unit (specified in type)"
type UnitPrice {
  amount: Float!
  unitWeight: Float # Necessary for price type UNIT
  publicWeightPrice: Float # Parameter to calculate price in kg for PACKAGE type
  "Enable user to configure the price in grams"
  showAsGrams: Boolean 
  type: PriceType
}

input UnitPriceInput {
  amount: Float!
  unitWeight: Float
  publicWeightPrice: Float
  showAsGrams: Boolean
  type: PriceType!
}

# Changes:
# WEIGHT g -> kg
