type TimeSlot {
  day: Day!
  startTime: Time!
  endTime: Time!
}

input TimeSlotInput {
  day: DayInput!
  startTime: TimeInput!
  endTime: TimeInput!
}

type Day {
  date: Int!
  month: Int!
  year: Int!
}

input DayInput {
  date: Int!
  month: Int!
  year: Int!
}

type Time {
  hours: Int!
  minutes: Int!
}

input TimeInput {
  hours: Int!
  minutes: Int!
}
